#!/usr/bin/env python3
"""
Generates the two documents that must never drift from the code:

    docs/TAGS.md   the tag vocabulary, its rules, and live counts
    CREDITS.md     per-repo attribution, licenses and the pinned commit

Both are derived from tools/taxonomy.py + data/meta.json, so they are
regenerated by every build rather than maintained by hand.

    python3 tools/gen_docs.py
"""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import taxonomy as T


def tags_md(meta):
    counts = meta["tag_counts"]
    out = [
        "# Tag vocabulary",
        "",
        "*Generated by `tools/gen_docs.py` — edit `tools/taxonomy.py`, not this file.*",
        "",
        "Every tag is `facet:value`. Facets are independent axes, so a filter",
        "combines with **AND** across facets and **OR** within one facet:",
        "selecting *domain:animation* and *domain:design* plus *stack:react* means",
        "\"(animation OR design) AND react\".",
        "",
        "## How a tag is assigned",
        "",
        "Each tag owns a list of case-insensitive regexes. A match scores by the field it landed in:",
        "",
        "| Field | Weight | Why |",
        "|---|---|---|",
        "| skill `name` | 6 | the author's own summary of the thing |",
        "| directory `path` | 6 | scoped *below* the source root, so repo folder names never leak in |",
        "| `description` | 5 | the only text an agent sees at discovery time |",
        "| body headings | 2 | structural, but often aspirational |",
        "| body prose | 1 | capped at 3 total — mentions are cheap |",
        "",
        f"A tag fires at **score ≥ {T.THRESHOLD}**. In practice: *a hit in the name, the path or the",
        "description fires the tag; a body-only mention needs both a heading and repeated prose.*",
        "One hit per field per tag — repeating a word does not add weight.",
        "",
        "Per-skill caps keep cards readable: "
        + ", ".join(f"{k} ≤ {v}" for k, v in
                    {"domain": 3, "capability": 3, "stack": 6, "format": 3, "agent": 2}.items())
        + ". Trait tags are uncapped because they are facts, not guesses.",
        "",
        "Tagging is **deterministic**: the same clone always produces the same tags, so",
        "`data/index.json` diffs are meaningful in review.",
        "",
        "## Facets",
        "",
    ]
    for facet in T.FACETS:
        tags = sorted(t for t in counts if t.startswith(facet + ":"))
        if not tags:
            continue
        out += [f"### `{facet}` — {T.FACET_LABELS.get(facet, facet)}", ""]
        if facet == "trait":
            out += ["Derived from the file tree and frontmatter, never from keywords — always true.", ""]
        out += ["| Tag | Skills | Matches on |", "|---|--:|---|"]
        for t in sorted(tags, key=lambda x: -counts[x]):
            pats = T.RULES.get(t)
            if pats:
                shown = ", ".join(f"`{p}`" for p in pats[:4])
                if len(pats) > 4:
                    shown += f" *(+{len(pats) - 4})*"
            else:
                shown = "*structural*"
            out.append(f"| `{t}` | {counts[t]} | {shown} |")
        out.append("")
    out += [
        "## Adding or changing a tag",
        "",
        "1. Edit `RULES` in `tools/taxonomy.py`.",
        "2. Run `python3 tools/build.py` — tags, counts and this file are all regenerated.",
        "3. Check the diff on `data/index.json`. A rule that moves hundreds of skills is",
        "   usually too broad; anchor it with `\\b` or move it to `NAME_PATH_ONLY`.",
        "",
        "Short, ambiguous tokens are the usual failure mode. `\\bgo\\b` matches the English",
        f"verb, so *stack:go* lives in `NAME_PATH_ONLY` ({', '.join(sorted(T.NAME_PATH_ONLY))}) and",
        "only fires from a name or path.",
        "",
    ]
    return "\n".join(out)


def credits_md(meta):
    out = [
        "# Credits",
        "",
        "*Generated by `tools/gen_docs.py`.*",
        "",
        "Every skill indexed here was written by someone else. This repository holds an",
        "**index**, not a fork: it changes no upstream licensing, and every install path",
        "pulls from the original repository.",
        "",
        "Where a source's license permits redistribution, this project also carries the",
        "`SKILL.md` text so the interface can render it offline. That text stays under its",
        "upstream license, and each license is reproduced verbatim in [`licenses/`](licenses/).",
        "Sources whose repository declares **no** license are **indexed only**: their",
        "metadata is recorded, their text is not, and the interface fetches it from the",
        "source repository at read time.",
        "",
        f"Indexed {meta['skill_count']} skills from {meta['source_count']} repositories on "
        f"{meta['built_at'][:10]}.",
        "",
    ]
    for s in meta["sources"]:
        out += [
            f"## {s['author']} — [{s['repo']}]({s['url']})",
            "",
            s["blurb"],
            "",
            f"- **Skills indexed:** {s['count']}",
            f"- **License:** {s['license']}"
            + (f" — [full text](licenses/{s['id']}-LICENSE.txt)" if s.get("redistribute", True) else ""),
            f"- **Redistribution:** " + ("`SKILL.md` text included in this repository"
                                         if s.get("redistribute", True) else
                                         "**indexed only — text not carried here**"),
            f"- **Pinned at:** `{s['commit']}`" + (f" ({s['committed_at'][:10]})" if s.get("committed_at") else ""),
            f"- **Author:** {s['author_url']}",
        ]
        if s.get("license_note"):
            out += ["", f"> {s['license_note']}"]
        out += [""]
    out += [
        "## If you are one of these authors",
        "",
        "If you would rather this project not carry your skills' text, open an issue and",
        "it will be switched to indexed-only in the next build — set `\"redistribute\": false`",
        "on your entry in `sources.json`. If your repository has no license and you would",
        "like the text carried, adding a `LICENSE` upstream is all it takes.",
        "",
        "## Format",
        "",
        "Skills follow the open [Agent Skills specification](https://agentskills.io/specification),",
        "originally developed by Anthropic and released as an open standard.",
        "",
        "## This repository",
        "",
        "The indexing tools, tag taxonomy, forge score and browser interface in this repo are",
        "original work. The skills they describe are not — see each entry's license above, and",
        "respect it when you install, adapt or redistribute a skill.",
        "",
        "Skills whose upstream repository declares no license are marked **Unspecified**. Absence",
        "of a license is not permission: treat those as all-rights-reserved and ask the author",
        "before reusing them in anything you ship. This project does the same — it does not",
        "carry their text.",
        "",
    ]
    return "\n".join(out)


def copy_licenses(meta):
    """Ship each upstream license text. MIT and Apache-2.0 both require the
    license to travel with redistributed material; naming it in CREDITS.md is
    not enough. Copied from the clones so it is always the real upstream file."""
    import shutil
    out = ROOT / "licenses"
    out.mkdir(exist_ok=True)
    copied = []
    for s in meta["sources"]:
        src_dir = ROOT / "sources" / s["id"]
        found = None
        if src_dir.exists():
            for name in sorted(p.name for p in src_dir.iterdir() if p.is_file()):
                if name.lower().split(".")[0] in ("license", "licence", "copying"):
                    found = src_dir / name
                    break
        if found:
            dest = out / f"{s['id']}-LICENSE.txt"
            shutil.copyfile(found, dest)
            copied.append(s["id"])
    (out / "README.md").write_text(
        "# Upstream licenses\n\n"
        "*Generated by `tools/gen_docs.py` — verbatim copies from each source repository.*\n\n"
        "This project redistributes the `SKILL.md` text of the repositories listed in\n"
        "`sources.json`. MIT and Apache-2.0 both require their license text to accompany\n"
        "redistributed material, so the real upstream file is copied here for each source.\n\n"
        + "".join(
            f"- [`{s['id']}-LICENSE.txt`]({s['id']}-LICENSE.txt) — {s['author']} "
            f"([{s['repo']}]({s['url']}), {s['license']})\n"
            if s["id"] in copied else
            f"- **{s['author']}** ([{s['repo']}]({s['url']})) — no license file upstream; "
            f"indexed only, text not redistributed\n"
            for s in meta["sources"])
        + "\n## Statement of changes (Apache-2.0 §4b)\n\n"
          "`SKILL.md` bodies are redistributed verbatim — not edited, reformatted or\n"
          "translated. This project adds only derived metadata alongside them: tags, a\n"
          "quality score, size statistics and duplicate clustering, all produced by\n"
          "`tools/build.py`. No upstream file is modified.\n",
        encoding="utf-8")
    print(f"  wrote licenses/ ({len(copied)} upstream license files)")


def main():
    meta = json.loads((ROOT / "data" / "meta.json").read_text(encoding="utf-8"))
    copy_licenses(meta)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "TAGS.md").write_text(tags_md(meta), encoding="utf-8")
    (ROOT / "CREDITS.md").write_text(credits_md(meta), encoding="utf-8")
    print("  wrote docs/TAGS.md and CREDITS.md")


if __name__ == "__main__":
    main()
