#!/usr/bin/env python3
"""
Generates the two documents that must never drift from the code:

    docs/TAGS.md   the tag vocabulary, its rules, and live counts
    CREDITS.md     per-repo attribution, licenses and the pinned commit

Both are derived from tools/taxonomy.py + data/meta.json, so they are
regenerated by every build rather than maintained by hand.

    python3 tools/gen_docs.py
"""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import taxonomy as T


def tags_md(meta):
    counts = meta["tag_counts"]
    out = [
        "# Tag vocabulary",
        "",
        "*Generated by `tools/gen_docs.py` — edit `tools/taxonomy.py`, not this file.*",
        "",
        "Every tag is `facet:value`. Facets are independent axes, so a filter",
        "combines with **AND** across facets and **OR** within one facet:",
        "selecting *domain:animation* and *domain:design* plus *stack:react* means",
        "\"(animation OR design) AND react\".",
        "",
        "## How a tag is assigned",
        "",
        "Each tag owns a list of case-insensitive regexes. A match scores by the field it landed in:",
        "",
        "| Field | Weight | Why |",
        "|---|---|---|",
        "| skill `name` | 6 | the author's own summary of the thing |",
        "| directory `path` | 6 | scoped *below* the source root, so repo folder names never leak in |",
        "| `description` | 5 | the only text an agent sees at discovery time |",
        "| body headings | 2 | structural, but often aspirational |",
        "| body prose | 1 | capped at 3 total — mentions are cheap |",
        "",
        f"A tag fires at **score ≥ {T.THRESHOLD}**. In practice: *a hit in the name, the path or the",
        "description fires the tag; a body-only mention needs both a heading and repeated prose.*",
        "One hit per field per tag — repeating a word does not add weight.",
        "",
        "Per-skill caps keep cards readable: "
        + ", ".join(f"{k} ≤ {v}" for k, v in
                    {"domain": 3, "capability": 3, "stack": 6, "format": 3, "agent": 2}.items())
        + ". Trait tags are uncapped because they are facts, not guesses.",
        "",
        "Tagging is **deterministic**: the same clone always produces the same tags, so",
        "`data/index.json` diffs are meaningful in review.",
        "",
        "## Facets",
        "",
    ]
    for facet in T.FACETS:
        tags = sorted(t for t in counts if t.startswith(facet + ":"))
        if not tags:
            continue
        out += [f"### `{facet}` — {T.FACET_LABELS.get(facet, facet)}", ""]
        if facet == "trait":
            out += ["Derived from the file tree and frontmatter, never from keywords — always true.", ""]
        out += ["| Tag | Skills | Matches on |", "|---|--:|---|"]
        for t in sorted(tags, key=lambda x: -counts[x]):
            pats = T.RULES.get(t)
            if pats:
                shown = ", ".join(f"`{p}`" for p in pats[:4])
                if len(pats) > 4:
                    shown += f" *(+{len(pats) - 4})*"
            else:
                shown = "*structural*"
            out.append(f"| `{t}` | {counts[t]} | {shown} |")
        out.append("")
    out += [
        "## Adding or changing a tag",
        "",
        "1. Edit `RULES` in `tools/taxonomy.py`.",
        "2. Run `python3 tools/build.py` — tags, counts and this file are all regenerated.",
        "3. Check the diff on `data/index.json`. A rule that moves hundreds of skills is",
        "   usually too broad; anchor it with `\\b` or move it to `NAME_PATH_ONLY`.",
        "",
        "Short, ambiguous tokens are the usual failure mode. `\\bgo\\b` matches the English",
        f"verb, so *stack:go* lives in `NAME_PATH_ONLY` ({', '.join(sorted(T.NAME_PATH_ONLY))}) and",
        "only fires from a name or path.",
        "",
    ]
    return "\n".join(out)


def credits_md(meta):
    out = [
        "# Credits",
        "",
        "*Generated by `tools/gen_docs.py`.*",
        "",
        "Every skill indexed here was written by someone else. This repository holds an",
        "**index**, not a fork: it changes no upstream licensing, and every install path",
        "pulls from the original repository.",
        "",
        "It records each skill's metadata — name and description as written upstream, plus",
        "derived tags, score and size — and carries **no `SKILL.md` text**. The interface",
        "reads each skill live from its source repository when you open it. Upstream",
        "licenses are reproduced verbatim in [`licenses/`](licenses/) for attribution.",
        "Sources whose repository declares **no** license are marked **Unspecified**.",
        "",
        f"Indexed {meta['skill_count']} skills from {meta['source_count']} repositories on "
        f"{meta['built_at'][:10]}.",
        "",
    ]
    for s in meta["sources"]:
        out += [
            f"## {s['author']} — [{s['repo']}]({s['url']})",
            "",
            s["blurb"],
            "",
            f"- **Skills indexed:** {s['count']}",
            f"- **License:** {s['license']}"
            + (f" — [full text](licenses/{s['id']}-LICENSE.txt)" if s.get("redistribute", True) else ""),
            f"- **Pinned at:** `{s['commit']}`" + (f" ({s['committed_at'][:10]})" if s.get("committed_at") else ""),
            f"- **Author:** {s['author_url']}",
        ]
        if s.get("license_note"):
            out += ["", f"> {s['license_note']}"]
        out += [""]
    out += [
        "## If you are one of these authors",
        "",
        "This project keeps no copy of your text — it links to your repository and reads",
        "from it. If you would rather not be indexed at all, open an issue and your entry",
        "will be removed from `sources.json` in the next build.",
        "",
        "## Format",
        "",
        "Skills follow the open [Agent Skills specification](https://agentskills.io/specification),",
        "originally developed by Anthropic and released as an open standard.",
        "",
        "## This repository",
        "",
        "The indexing tools, tag taxonomy, forge score and browser interface in this repo are",
        "original work. The skills they describe are not — see each entry's license above, and",
        "respect it when you install, adapt or redistribute a skill.",
        "",
        "Skills whose upstream repository declares no license are marked **Unspecified**. Absence",
        "of a license is not permission: treat those as all-rights-reserved and ask the author",
        "before reusing them in anything you ship.",
        "",
    ]
    return "\n".join(out)


def copy_licenses(meta):
    """Ship each upstream license text for attribution: names and descriptions
    are quoted from upstream even though no SKILL.md text is carried. Copied
    from the clones so it is always the real upstream file."""
    import shutil
    out = ROOT / "licenses"
    out.mkdir(exist_ok=True)
    copied = []
    for s in meta["sources"]:
        src_dir = ROOT / "sources" / s["id"]
        found = None
        if src_dir.exists():
            for name in sorted(p.name for p in src_dir.iterdir() if p.is_file()):
                if name.lower().split(".")[0] in ("license", "licence", "copying"):
                    found = src_dir / name
                    break
        if found:
            dest = out / f"{s['id']}-LICENSE.txt"
            shutil.copyfile(found, dest)
            copied.append(s["id"])
    (out / "README.md").write_text(
        "# Upstream licenses\n\n"
        "*Generated by `tools/gen_docs.py` — verbatim copies from each source repository.*\n\n"
        "This project indexes the repositories listed in `sources.json`. It carries no\n"
        "`SKILL.md` text, only metadata — including each skill's name and description as\n"
        "written upstream — so each upstream license is copied here for attribution.\n\n"
        + "".join(
            f"- [`{s['id']}-LICENSE.txt`]({s['id']}-LICENSE.txt) — {s['author']} "
            f"([{s['repo']}]({s['url']}), {s['license']})\n"
            if s["id"] in copied else
            f"- **{s['author']}** ([{s['repo']}]({s['url']})) — no license file upstream; "
            f"indexed only\n"
            for s in meta["sources"])
        + "\n## What is taken from upstream\n\n"
          "Only each skill's `name` and `description`, quoted unmodified, and its list of\n"
          "bundled file paths. Everything else is derived by `tools/build.py`: tags, a\n"
          "quality score, size statistics and duplicate clustering. No upstream file is\n"
          "copied or modified.\n",
        encoding="utf-8")
    print(f"  wrote licenses/ ({len(copied)} upstream license files)")


def main():
    meta = json.loads((ROOT / "data" / "meta.json").read_text(encoding="utf-8"))
    copy_licenses(meta)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "TAGS.md").write_text(tags_md(meta), encoding="utf-8")
    (ROOT / "CREDITS.md").write_text(credits_md(meta), encoding="utf-8")
    print("  wrote docs/TAGS.md and CREDITS.md")


if __name__ == "__main__":
    main()
